setup_userinfo:
    resource: "@SetupBundle/Resources/config/routing/userinfo.yml"
    prefix:   /userinfo

setup_user:
    resource: "@SetupBundle/Resources/config/routing/user.yml"
    prefix:   /user

setup_school:
    resource: "@SetupBundle/Resources/config/routing/school.yml"
    prefix:   /school

setup_question:
    resource: "@SetupBundle/Resources/config/routing/question.yml"
    prefix:   /question

setup_questiontype:
    resource: "@SetupBundle/Resources/config/routing/questiontype.yml"
    prefix:   /questiontype

setup_classification:
    resource: "@SetupBundle/Resources/config/routing/classification.yml"
    prefix:   /classification

setup_homepage:
    path:     /setup/
    defaults: { _controller: SetupBundle:Default:index }
