<?php

namespace Capstone\SetupBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query\ResultSetMapping;
/**
 * QuizQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
  public function findQuestionA( $type, $difficulty, $points, array $question)
  {
  
  return $this->getEntityManager()
  ->createQuery("Select A from SetupBundle:Question A 
		where A.difficulty = '".$difficulty."' 
			AND A.points".$points."
			AND A.questionType='". $type."' 
			AND A.questionId NOT IN (".$question.")")->getResult();
	  
  }
  public function findQuestionB( $type, $difficulty, $points)
  {
      return $this->getEntityManager()
	    ->createQuery("Select A from SetupBundle:Question A 
		where A.difficulty = '".$difficulty."' 
			AND A.points".$points."
			AND A.questionType='". $type."'")->getResult();	  
  }
}