<?php

namespace Capstone\SetupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizQuestionRepository extends EntityRepository
{
}
