<?php

namespace Capstone\SetupBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
    
  public function findRegion($region){
      
      
	  return $this->getEntityManager()
            ->createQuery("SELECT A.schoolId, A.school, B.parish from SetupBundle:School A JOIN SetupBundle:Parish B WHERE A.parish = B.parishId and B.parish='".$region."'")->getResult();
      }
}