<?php

namespace Capstone\SetupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInfoRepository extends EntityRepository
{

    public function findBySchool($school){
	return $this->getEntityManager()->createQuery("Select A  from SetupBundle:UserInfo A where A.school='" .$school."'")->getResult();
    
    }
    
    public function findByClass ($class) {
	return $this->getEntityManager()->createQuery("Select A  from SetupBundle:UserInfo A where A.class='" .$class."'")->getResult();
    }
    
    public function findRegionalResult()
    {
	return $this->getEntityManager()->createQuery("SELECT Count(A) from SetupBundle:UserInfo A Group BY A.school")->getResult();
    }
}
