<?php

namespace Capstone\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
	public function schoolReport($school) {
		
		$em = $this->getDoctrine()->getManager();
		$report = $em->getRepository('SetupBundle: UserInfo')->findAll($school);
		if (!$report){
			throw $this->createNotFoundException(
				'No School found for school '.$school
				);
			}
		
		return $report;



}


