Capstone\ReportBundle\Entity\Questiontype:
    type: entity
    table: QuestionType
    id:
        questionType:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            id: true
            column: question_type
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
