Capstone\ReportBundle\Entity\QuizQuestion:
    type: entity
    table: QuizQuestion
    repositoryClass: Capstone\ReportBundle\Entity\QuizQuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        questionID:
            type: integer
            column: question_ID
        answer:
            type: string
            length: '2'
    lifecycleCallbacks: {  }
