Capstone\ReportBundle\Entity\QuizResults:
    type: entity
    table: null
    repositoryClass: Capstone\ReportBundle\Entity\QuizResultsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        correctQuestions:
            type: integer
            column: correct_questions
        incorrectQuestions:
            type: integer
            column: incorrect_questions
    lifecycleCallbacks: {  }
