school:
    path:     /
    defaults: { _controller: "SetupBundle:School:index" }

school_show:
    path:     /{id}/show
    defaults: { _controller: "SetupBundle:School:show" }

school_new:
    path:     /new
    defaults: { _controller: "SetupBundle:School:new" }

school_create:
    path:     /create
    defaults: { _controller: "SetupBundle:School:create" }
    methods:  POST

school_edit:
    path:     /{id}/edit
    defaults: { _controller: "SetupBundle:School:edit" }

school_update:
    path:     /{id}/update
    defaults: { _controller: "SetupBundle:School:update" }
    methods:  [POST, PUT]

school_delete:
    path:     /{id}/delete
    defaults: { _controller: "SetupBundle:School:delete" }
    methods:  [POST, DELETE]
