userinfo:
    path:     /
    defaults: { _controller: "SetupBundle:UserInfo:index" }

userinfo_show:
    path:     /{id}/show
    defaults: { _controller: "SetupBundle:UserInfo:show" }

userinfo_new:
    path:     /new
    defaults: { _controller: "SetupBundle:UserInfo:new" }

userinfo_create:
    path:     /create
    defaults: { _controller: "SetupBundle:UserInfo:create" }
    methods:  POST

userinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "SetupBundle:UserInfo:edit" }

userinfo_update:
    path:     /{id}/update
    defaults: { _controller: "SetupBundle:UserInfo:update" }
    methods:  [POST, PUT]

userinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "SetupBundle:UserInfo:delete" }
    methods:  [POST, DELETE]
