report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /admin/report

quiz:
    resource: "@QuizBundle/Resources/config/routing.yml"
    prefix:   /quiz

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

setup:
    resource: "@SetupBundle/Resources/config/routing.yml"
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
     path: /home/
     defaults:
        _controller: FrameworkBundle:Template:template
        template:    "admin/layout.html.twig"
        
