file:
    resource: "@FileBundle/Controller/"
    type:     annotation
    prefix:   /

report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /report

quiz:
    resource: "@QuizBundle/Resources/config/routing.yml"
    prefix:   /quiz

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

setup:
    resource: "@SetupBundle/Resources/config/routing.yml"
    prefix:   /admin/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
     path: /
     defaults:
        _controller: FrameworkBundle:Template:template
        template:    "admin/layout.html.twig"
reports:   
     resource: "@ReportBundle/Controller/"
     prefix: /report/tab/
     type: annotation

about:
     path: /about/
     defaults:
        _controller: FrameworkBundle:Template:template
        template:    "admin/about.html.twig"
fun:
   resource: "@QuizBundle/Controller/"
   prefix: /app/
   type: annotation
   
user_routes:
   resource: "@UserBundle/Controller/"
   type: annotation
   
files:
   resource: "@FileBundle/Resources/config/routing.yml"
   prefix:   /file
   
quiz_answer:
    pattern: "/reply.{format}/"
    defaults: { _controller: "QuizBundle:Quiz:getAnswer", format:html }
    requirements:
        format: json
# api:

#    path: /api/
#    defaults:
#        _controller: FrameworkBundle:Template:template
#        template: "/var/www/html/FunQ/vendor/phpdocumentor/phpdocumentor/output/index.html.twig"
#