user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
