# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Capstone\SetupBundle\Entity\User: 
            algorithm : sha512
        #Symfony\Component\Security\Core\User\User: plaintext
          #  algorithm : bcrypt
          #   cost : 12
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_database_users:
           entity: { class: SetupBundle:User }
        #in_memory:
        #   memory:
        #      users:
        #          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: /login
            logout:
                path: logout
                target: login_form
            anonymous: ~
            switch_user: ~
            remember_me:
                key: "Order 1138"
        #main:
        #    anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    role_hierarchy:
        ROLE_EXPERT: [ROLE_USER ] #for questions and view algorithm
        ROLE_ADMIN:       [ROLE_USER, ROLE_USER_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: ROLE_USER }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new, roles: ROLE_ADMIN }
        - { path: ^/create, roles: ROLE_USER }