Capstone\SetupBundle\Entity\Classification:
    type: entity
    table: Classification
    id:
        classificationIq:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            id: true
            column: Classification_IQ
            generator:
                strategy: IDENTITY
    fields:
        classify:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            column: Classify
    lifecycleCallbacks: {  }
