Capstone\SetupBundle\Entity\QuizQuestion:
    type: entity
    table: QuizQuestion
    repositoryClass: Capstone\SetupBundle\Entity\QuizQuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        answer:
            type: string
            length: '2'
    manyToOne:
        quiznum:
            targetEntity: Quiz
            cascade: {   }
            mappedBy: null
            inversedBy: null
            joinColumn:              
               referencedColumnName: quiznum
               onDelete: CASCADE
              
        questionID:
            targetEntity: Question
            cascade: {   }
            mappedBy: null
            inversedBy: null
            joinColumn:               
               referencedColumnName: question_ID
               onDelete: CASCADE
              
    
    lifecycleCallbacks: {  }
