Capstone\SetupBundle\Entity\School:
    type: entity
    table: school
    repositoryClass: Capstone\SetupBundle\Entity\SchoolRepository
    indexes:
        parish_id:
            columns:
                - parish_id
    id:
        schoolId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: school_id
            generator:
                strategy: IDENTITY
    fields:
        school:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        parish:
            targetEntity: Parish
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parish_id:
                    referencedColumnName: parish_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
