Capstone\SetupBundle\Entity\User:
    type: entity
    table: User
    uniqueConstraints:
        Email:
            columns:
                - Email
    id:
        userid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: UserID
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Username
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Email
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: Password
        roles:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
              
    lifecycleCallbacks: {  }
