Capstone\SetupBundle\Entity\UserInfo:
    type: entity
    table: UserInfo
    repositoryClass: Capstone\SetupBundle\Entity\UserInfoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: FirstName
            nullable: true
        lastName:
            type: string
            length: 255
            column: LastName
            nullable: true
        birthdate:
            type: date
            column: Birthdate
            nullable: true
        gender:
            type: string
            length: '2'
            column: Gender
            nullable: true
        school:
            type: string
            length: 255
            column: School
            nullable: true
        class:
            type: string
            length: 255
            column: Class
            nullable: true
        parish:
            type: string
            length: 255
            column: Parish
            nullable: true
        iQ:
            type: integer
            column: IQ
            nullable: true
    
               
    lifecycleCallbacks: {  }
