 
<?php

namespace Capstone\FileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestiontypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
} 